import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>SUREDEAL</title>
      </head>
      <body>
        <main className="flex h-screen w-full max-md:mt-15">
          <div className="relative hidden md:block w-1/2 h-full">
            <Image
              src="/images/sideimage.png"
              alt="Decorative side"
              fill
              className="object-cover"
            />
          </div>

          <div
            className={`
          relative
          flex items-center justify-center
          w-full md:w-1/2 h-full
          bg-[url('/images/sideimage.png')] bg-cover bg-center
          md:bg-none      
        `}
          >
            <div className="absolute inset-0 bg-black/40 md:hidden" />

            <div className="relative z-10 w-full max-w-md p-8  md:bg-white rounded-xl ">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
